fix: calendar example
Fixes the `TypeError: CalendarDaysView.__init__() missing 1 required positional argument: 'config'` error when running `/example/mega/bot.py/.